### ISSUE TITLE
Hyper-parameter d_model

### ISSUE THREAD

**Issue by pys16** [drdh/Synergy-RL#2]
Hello! I've been trying to reproduce the Synergy-RL experiments, but I'm having trouble to find a proper value for the hyper-parameter d_model. Have tried d_model=1 as readme.md suggests but it performs badly; d_model=64 as argument.py suggests works much better, but still some gap from the original performance in the paper. I'm not sure whether the results are just caused by random seeds or I'm not using the proper hyper-paremeters. Can you share the original parameters used in the paper?

**Comment by drdh** [comment]
Thank you for your interest in our work. We use `d_model=64`. 

This bad result might be caused by random seeds. But, the average performance should match the results reported in our paper. 

Please let us know if you encounter other problems.

**Comment by pys16** [comment]
Thank you very much for your helpful reply! I'll try more random seeds.
